/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hair_hairstyle_test_NDKJniUtils */

#ifndef _Included_com_hair_hairstyle_test_NDKJniUtils
#define _Included_com_hair_hairstyle_test_NDKJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hair_hairstyle_test_NDKJniUtils
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hair_hairstyle_test_NDKJniUtils_getStr
  (JNIEnv * env, jobject){
     return env->NewStringUTF("jjjio");
  }

#ifdef __cplusplus
}
#endif
#endif
